using Day15HashTable;
UC1MyMapNode<string, string> hashTable = new UC1MyMapNode<string, string>(5);
hashTable.Add("0", "To");
hashTable.Add("1", "be");
hashTable.Add("2", "or");
hashTable.Add("3", "not");
hashTable.Add("4", "to");
hashTable.Add("5", "be");
string hash0 = hashTable.Get("0");
Console.WriteLine("0th index value: " + hash0);
string hash1 = hashTable.Get("1");
Console.WriteLine("1st index value: " + hash1);
string hash2 = hashTable.Get("2");
Console.WriteLine("2nd index value: " + hash2);
string hash3 = hashTable.Get("3");
Console.WriteLine("3rd index value: " + hash3);
string hash4 = hashTable.Get("4");
Console.WriteLine("4th index value: " + hash4);
string hash5 = hashTable.Get("5");
Console.WriteLine("5th index value: " + hash5);